# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 3fb5cf1b2658f369dff70c1adfd705fc1edd3ae8e9e62c132f0eeb791810d81ef2152ff8f638751a21d3a6001020261d4500d3dfb66fe6c52c28633b71053956

test:
  secret_key_base: 02b3b4517d440ce1ab277e8c596c320fdafcdabec1a665856fd576abe52caef4f9f99601fa4101c3df38a91cf24596e3ded6ce86db681ab1b22277d306237444

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
